/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 shuma-gorath.gltf --transform 
Files: shuma-gorath.gltf [198.75MB] > shuma-gorath-transformed.glb [5.09MB] (97%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const baseUrl = "https://sethrhod.github.io/portfolio-project";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    `{${baseUrl}/shuma-gorath-transformed.glb`
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["shuma-gorath7"].geometry}
        material={nodes["shuma-gorath7"].material}
      />
    </group>
  );
}

useGLTF.preload(`{${baseUrl}/shuma-gorath-transformed.glb`);
